### ISSUE TITLE
Issue for the amp classifier and mic classifier in the model Hydramp

### ISSUE THREAD

**Issue by liuxianliang-icrc** [szczurek-lab/hydramp#4]
I just would like to know how well does the amp classifier and mic classifier perform in your model HydrAMP. Becasue I have found that the amp value and mic value of Non-AMP predicted by the given amp classifier and mic classifier is so high that they are as high as AMP, so I would like to know do the amp classifier and mic classifier have some problems?
![image](https://user-images.githubusercontent.com/62138260/235068617-1b2316e6-92f7-4116-8048-cf54f4481b08.png)

**Comment by prokotg** [comment]
Hi, thanks for raising this. We've got a bug in a *service* code where parameters are not properly passed down so positives are always  generated by default. We're working on fixing this as well as rolling out some updates.  Apologies for the inconvenience

**Comment by prokotg** [comment]
This has been resolved. The service was updated. Thanks!
